<?

/*
Do not edit this file
*/

$templates['pagelayout'] = "pagelayout.php";
$templates['text'] = "text.php";
$templates['new'] = "new.php";
$templates['edit'] = "edit.php";
$templates['links'] = "links.php";
$templates['show'] = "show.php";

?>